### ISSUE TITLE
Custom events on components

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#10]
It'd be useful to create custom events for components that can be used in the same way as primitive events.

```lua
local SomeComponent = Roact.Component:extend("SomeComponent")

function SomeComponent:init()
    self.CustomEvent = Roact.createEvent()
end

function SomeComponent:render()
    -- Render the component, somewhere in here fire self.CustomEvent
end

local element = Roact.createElement(SomeComponent, {
    [Roact.Event.CustomEvent] = function(rbx, option)
        print(option)
    end,
})
```

Thought: Should the event be fired with the element that the custom event was declared on (so in the above example, `rbx == element`)? If so, how do you get the underlying Roblox object? I'm not sure how best to do this, or if it's even useful - maybe I'm missing something obvious here.

**Comment by LPGhatguy** [comment]
You can just pass a normal function with a regular key to a component to emulate the event mechanics that Roact has!

For example, you might implement a 'fancy' button like this:

```lua
-- We accept an 'onClick' callback, which operates just like Roact's built-in
-- event mechanics
local function FancyButton(props)
	return Roact.createElement("TextButton", {
		Text = "So Fancy!",

		[Roact.Event.MouseButton1Click] = function(rbx)
			if props.onClick then
				props.onClick(rbx, "fancy value")
			end
		end,
	})
end

-- Then, to use it:
Roact.createElement(FancyButton, {
	onClick = function(rbx, value)
		print("The button", rbx, "was clicked with a value of", value)
	end,
})
```

This is essentially all that Roact is doing under the hood when you pass a prop that uses `Roact.Event`, it just has a weird prop key to avoid colliding with other properties on objects and make sure that Roact knows it's an event we're trying to connect to.

**Comment by AmaranthineCodices** [comment]
Ooh, neat! Thanks a bunch. I'll close this now.
