### ISSUE TITLE
Obsolete Portals?

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#118]
`Core.Portal` might be an obsolete component type. After staring at them for a long while, I don't understand a couple things:
- why can't portal's apply their props to what instance they are pointing to?
- why can't primitive elements have a `Core.Target` property to replace portals? (preventing instance creation)

Using `Core.Target` instead of `target` allow the property to be caught down in `setProps` in its `userdata` prop name type case, essentially making the primitive components and portals reconciled the same beside the differences mentioned above.

**Comment by LPGhatguy** [comment]
I think there's a lot of value in separating the concepts of "make a new thing" from "put some stuff in this other thing." Notably, it's really valuable to know early on in reading a block that it's a portal, whereas a special property key could be hidden!

The big reason why we wouldn't want to apply props to a portal is that we have no idea what other code could be handling that instance! There's not really a sound way to undo the changes that we'd apply when we're done, especially if another piece of code, Roact or not, also mutates the object.
