### ISSUE TITLE
Prevent constant component type checking

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#125]
I'm currently working on a slightly different system like Roact for my personal use, but I thought you may like some of the insights that I've gained while working on it. This is the first issue that I've made based upon these insights. I might come back and post some more when it strikes me I haven't posted them.

Right now the mount, reconcile, and unmount functions have the same implementation for every component type. Each has couple if statements inside of them to special case some branches of logic. I propose splitting these functions apart, so that they can be associated with the instance in the mount function. This effectively stores the result of the comparison for future use, alleviating the need to check in the reconcile and unmount functions. The mount function can also remain free of special casing because it can get the component from a lookup table using the component type as the index, and simply tailcall the component's mount method.

These changes make the code more readable and eliminates the overhead associated with component type checks in the reconcile and unmount functions. As a minor side advantage, it also makes the code base more uniform: why do stateful components have a module, but primitive and functional do not?

**Comment by LPGhatguy** [comment]
I'm going to do something along these lines in the new reconciler, but it's a little bit different. As opposed to storing methods on the actual nodes, I precompute what kind of element is stored with each node by figuring it out in `createElement` instead.

Breaking apart the actual functions for mount/reconcile/unmount seems like a good idea, but there'd still probably be a top-level function that branches and figures out which one to call.
