### ISSUE TITLE
Remove functional elements from instance tree

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#126]
Functional elements serve no purpose in the instance tree, but add overhead when their instance handle is created/maintained/destroyed. Because they are 1 to 1, their existence can be gathered from their parent's output, and their end result is their child. If in a snapshot it is useful to view functional components as well, then the parent's render method can be called to see if the resultant element is a functional component. If it is, the functional component can be called, to determine if its child is a functional component, and so on. 

What I propose is that when functional components are mounted, their child is mounted in their place (if its child is a functional component, then this becomes a recursive process). When the reconciler runs, if render's output is a functional component, then it is evaluated until it results in a primitive or stateful component, at which point normal reconciliation continues. When unmount is run, it will never run into a functional component in the tree.

**Comment by LPGhatguy** [comment]
There are tools in the JS ecosystem to inline components that might be relevant at some future date if we want to do the same thing for Lua and Roact.

In the meantime, I want to move the _other_ direction: Function components should be more useful, starting with letting them return multiple children. Inlining them at that point wouldn't really be feasible anymore!
