### ISSUE TITLE
Rename primitive components

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#127]
Functional, and Stateful are excellent names to describe their objective, but Primitive is easily misinterpreted as simple rather than the base functionality we are building on. Two other names for primitive elements that also carry a lot of meaning are Concrete and Interface. 

A Concrete Component is a component that isn't abstract; it actually exists in the "real world," whatever that means. However, this name creates an interesting dichotomy. If we have abstract stateful, abstract functional, and concrete stateful, then shouldn't we also have concrete functional components? Perhaps concrete functional components would be an interesting feature to add (external method calling in a roact way, without making render impure or hiding the call in an event's callback).

The other possible name for a Primitive Component, an Interface Component, focuses less on the concept of building on an existing structure; it elevates Roact from being an addon to the real world to being a world of its own, and interface components are an interface between the Roact world and another world. This abstraction also makes another point clearer: the Roact world can interface with any other given world if given the proper linkage. Perhaps in the future Roact could broaden its horizons from the physical Roblox world to other APIs including but not limited to networking without external code editing a Rodux store to alter Roact state, through props.

**Comment by lunaticAnn** [comment]
I am not sure about Concrete but Interface seems a little confusing..? I feel primitive is more understandable to me, as a lot of time when we build virtual trees for other algorithms like bvh, the leaf nodes are mostly the real thing we operate on..? Not sure. My English is not really well.

**Comment by LPGhatguy** [comment]
The React terminology for these is "host components" -- I think I like that more than primitive.
