### ISSUE TITLE
Implement component registration

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#129]
I may have mentioned this while I was in the office, but allowing components to be registered with Roact, allowing their use without requiring them in every file, would be fantastic! This is how I imagine it would be implemented:

Every component that uses another component can use its name as a string as the component argument to createElement. (Or, you know, we could scrap createElement and simply insert a Roact.Component prop into elements as I suggested earlier.) Each Component's source would be located in a standard location (such as a descendent of a file, as it is now). Roact would go through this location and create a placeholder for each component and store that in a list of registered components. When a string component is mounted, it first checks the list of registered components. If a registered component exists, then it calls its mount method (this is assuming that #125 is implemented, otherwise using the __index metamethod would give the desired functionality). If the component is a placeholder, then it will require the component and properly insert it into the registered components before calling that component's mount method (or returning the proper index). Reconciling and unmounting happen similarly. Note that the unloaded placeholder loads components in transparently if they are ever used. 

This change removes the maintenance required to upkeep component references at the top of many files. If a component was ever going to change locations, all references to it would also have to change. In addition, when a new file is created, developers need to go through and copy the references to components they are using from additional files. Finally, the references must be removed when code is refactored the components once referenced are no longer used.

Removing those extra lines also allows developers to focus more on what matters: the implementation of functionality they are looking at, not what it relies upon. Say "NO!" to scrolling down to get to what your looking for!

A disadvantage to this is that a search must be done in the root component folder to find the source for a given component instead of having it listed and upkept in every file you might find a reference to it (seems like an ok tradeoff to me).

Another disadvantage to this is that all components must have different names, (or the loader will warn) and could intercept the mounting of all primitive components. While this bug makes for a nice feature, this can be avoided by Roact making the registered or similar list available so that the values of that list could be used in the component argument of createElement instead of a string.

(Edit: Oh yes, this also allows the registration of both functional and stateful components)

**Comment by LPGhatguy** [comment]
Explicitly loading components and declaring them as dependencies of your module is a feature, not a bug.
