### ISSUE TITLE
Functional components should have access to context

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#13]
I'm using the context API to theme components in a hierarchy. At the moment this only works with stateful components, so every component has to be a "stateful" component, even when it actually has no state. React [allows the use of context in functional components](https://reactjs.org/docs/context.html#referencing-context-in-stateless-functional-components) by passing the context table as a parameter. It would be useful to have this functionality, or an equivalent, in Roact as well.

**Comment by LPGhatguy** [comment]
This is a good idea!

I'd like to revisit the context API to make it more friendly to access from stateful components and functional components.
