### ISSUE TITLE
Roact should reify booleans as nil

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#14]
I was trying to conditionally render Roact components like this:

```condition and Roact.createElement(...)```

This throws an error:
```
18:06:27.365 - ReplicatedStorage.Roact.Reconciler:238: Cannot reify invalid Roact element "false"
18:06:27.367 - Stack Begin
18:06:27.369 - Script 'ReplicatedStorage.Roact.Reconciler', Line 238 - field _reifyInternal
18:06:27.369 - Script 'ReplicatedStorage.Roact.Reconciler', Line 373 - field _reconcilePrimitiveChildren
18:06:27.370 - Script 'ReplicatedStorage.Roact.Reconciler', Line 291 - field _reconcile
18:06:27.370 - Script 'ReplicatedStorage.Roact.Component', Line 161 - method _forceUpdate
18:06:27.371 - Script 'ReplicatedStorage.Roact.Component', Line 127 - method _update
18:06:27.371 - Script 'ReplicatedStorage.Roact.Component', Line 114 - method setState
18:06:27.372 - Script 'ReplicatedStorage.RoactMaterial.Components.Checkbox', Line 35 - upvalue method
18:06:27.372 - Script 'ReplicatedStorage.Roact.SingleEventManager', Line 27
18:06:27.373 - Stack End
```

It's trivial to work around this (`condition and Roact.createElement(...) or nil`), but it would be nice if Roact would accept `boolean`s and render nothing regardless of the boolean's value. React has something similar - [React.Component.render](https://reactjs.org/docs/react-component.html#render) may return a boolean value, which results in nothing being rendered.

**Comment by LPGhatguy** [comment]
I like this idea, especially with precedent from React!
