### ISSUE TITLE
Check if Element is Visible in shouldUpdate for PureComponent

### ISSUE THREAD

**Issue by Dog2puppy** [Roblox/roact#140]
Currently, the Instance will update even if it's Visible property is set to false and it's a PureComponent. Adding a check could have performance benefits, and it will update the Instance anyways when the Instance is made visible.

**Comment by AmaranthineCodices** [comment]
This is a good idea, but I'm not sure it's really feasible:

* `shouldUpdate` doesn't know what `render` returned, so it has no way to know whether the `Visible` property even means anything!
* `PureComponent` doesn't handle individual elements, so I don't think it's the right place for that
* I'm not sure the overhead of checking for this property, then checking to make sure it's actually valid for the primitive class in question, etc.

You might consider writing your own `shouldUpdate` function for components where this behavior is desirable.

**Comment by Dog2puppy** [comment]
Okay. I'll close this then. I guess parts and stuff like that don't have `Visible` (or atleast I don't think so) and Roact can handle parts, so I'll close this. Could be something to look at in the future.
