### ISSUE TITLE
API should have PascalCase options

### ISSUE THREAD

**Issue by dnurkkala** [Roblox/roact#143]
For example,

`Roact.createElement(Roact.Portal, {
   Target = ...
})`

Should be possible in addition to the normal

`Roact.createElement(Roact.Portal, {
    target = ...
})`

As a person who prefers PascalCase for all of my property assignments (and since Roblox uses PascalCase for properties as well), this can really come around to bite me. It'd be nice to have the option.

**Comment by LPGhatguy** [comment]
I think I'm going to close this in favor of #142.

I wonder if it would be practical to write a library case transformer thing so you could use any library as whatever case you want.

**Comment by Dog2puppy** [comment]
Having this for Functions would also be nice. Being able to do `Roact:CreateElement()` would be nice.
