### ISSUE TITLE
Symbol.lua is missing from the final lib

### ISSUE THREAD

**Issue by Kylaaa** [Roblox/roact#190]
the master branch has Symbol as a child of Roact, this branch does not.

**Comment by LPGhatguy** [comment]
Which branch are you referring to?

**Comment by Kylaaa** [comment]
new-reconciller

**Comment by ZoteTheMighty** [comment]
No problem! So were you looking for Symbol as part of Roact's public interface? That's neither true in `master` nor in `new-reconciler`. You may have been grabbing it out of Roact in the past in some way (reaching into `CorePackages.RoactImpl`?), but I'd recommend just copying the file over to wherever you need it. It's a pretty dead simple pattern, I wouldn't be too concerned about duplicating it.
