### ISSUE TITLE
Updating from having children to having `nil` children doesn't remove children

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#209]
This is something I hit in Rojo trying to upgrade to Roact 1.0!

When an update causes a change from:

```lua
Roact.createElement("Parent", nil, { Child = Roact.createElement("Folder") })
```
to
```lua
Roact.createElement("Parent", nil, nil)
```

the `Child` folder won't be removed. If children is specified as an empty table instead, the object appears to be removed.

Here's the relevant component in Rojo: https://github.com/LPGhatguy/rojo/blob/1e130971269367da2f58c8a78b464cfcd26650af/plugin/src/Components/App.lua#L82-L142

Changing line 83 from `local children` to `local children = {}` fixes the Rojo bug.

**Comment by AmaranthineCodices** [comment]
There's two ways we can fix this, I think:

* Default `children` to `{}` in `createElement`
* Thread the `nil` through the reconciler and unmount everything when the element has `nil` children, skipping the diffing work.

I'm leaning towards the latter but the former would also work for fixing this.

**Comment by LPGhatguy** [comment]
I don't love the first option, since I think leaf elements are pretty plentiful. It'd be a shame to give them an extra unused table!

I think the second option might just boil down to fixing our child table iterator stuff to just return `nil` when the input is `nil`, and everything else should just work itself out, right?

**Comment by AmaranthineCodices** [comment]
This issue was introduced by ea822f62ec11be3f979344cc34e03b81e48b0b53.

**Comment by LPGhatguy** [comment]
Perfect, we should be able to just revert that?

I think it was a perf improvement change.

**Comment by AmaranthineCodices** [comment]
opened a PR to revert that commit in #210.
