### ISSUE TITLE
RobloxRenderer doesn't remove all children

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#217]
When reconciling a primitive component containing children with a element that doesn't have children then the children are not removed. If the new element has an empty list of children, the children are properly updated.

RobloxRender.updateHostNode at line 272 checks if the children are present in the new element, and if so add/removes children as needed. However, if the node had children but the new element does, it silently ignores the children.

RobloxRender.applyProp does receive the children property being set to nil but at line 112 ignores it but it a comment notes that it should be dealt with elsewhere.

**Comment by TylerRHoyer** [comment]
I suspect that RobloxRender.updateHostNode should call updateVirtualNodeWithChildren with an empty children list when the old element had children but the new element does not.

**Comment by TylerRHoyer** [comment]
This may be one of those bugs whose functionality is unknowingly being relied upon in current code bases. Submitting a fix and updating current code bases may be dangerous. Would you like me to submit a PR anyways?

**Comment by AmaranthineCodices** [comment]
Related: ea822f62ec11be3f979344cc34e03b81e48b0b53, #209, #210.

Does this still occur in latest `master`, or is this a duplicate of #209? If it is valid against current `master`, please provide a repro case, as I'm not quite understanding how this is different from that issue.

**Comment by TylerRHoyer** [comment]
Yup, it is a duplicate of #209

**Comment by TylerRHoyer** [comment]
Duplicate of #209
