### ISSUE TITLE
Event bindings do not respect Active property

### ISSUE THREAD

**Issue by honeytwin1** [Roblox/roact#244]
Roact.Event.MouseButton1Click still fires even when TextButton.Active = false

Repro: 
[EventConnections.zip](https://github.com/Roblox/roact/files/3991997/EventConnections.zip)

**Comment by LPGhatguy** [comment]
Hi, thanks for filing an issue!

I'm unsure that this is a Roact bug. Two notes:

* The `Active` property does not control whether input events will fire. You can try this without Roact -- `Activated` (a newer event) and `MouseButton1Click` will both fire even when `Active` is off.
* This feature is something that the Roblox engine handles, not Roact. That usually means that there's nothing we can do in Roact.

I'm going to go ahead and close this issue. If there's something I missed, feel free to reopen it and post a comment and we can look into this!
