### ISSUE TITLE
Returning nil in render doesn't allow that component to render anything else

### ISSUE THREAD

**Issue by Kampfkarren** [Roblox/roact#245]
If this is intentional, it's not documented.

If you have a component like:

```lua
local Foobar = Roact.Component:extend("Foobar")

function Foobar:render()
	if self.props.returnNil then
		return nil
	else
		return e("TextLabel", {
			Size = UDim2.fromScale(1, 1),
		})
	end
end
```

...and set the returnNil property to true, then false, it will not render the TextLabel.

**Comment by LPGhatguy** [comment]
This sounds like a bug! Do you have a small, complete repo, preferrably as an rbxl?

I'll take a stab at trying to reproduce it tomorrow. I would expect that this would work, since we use this pattern a lot in a lot of large Roact projects internally at Roblox

**Comment by Kampfkarren** [comment]
I will if I remember and get the chance!

**Comment by Kampfkarren** [comment]
Weird...seems that my repro works? Not sure what I was doing before :v
