### ISSUE TITLE
Roact tables shouldn't be cyclic

### ISSUE THREAD

**Issue by Jaguar-515** [Roblox/roact#268]
I'm trying to work with Roact and attempt to update a component on the server via a RemoteEvent on the client, however, a roadblock I have is that all tables that Roact generates (elements, components, RoactTrees, etc.) are cyclic.

It's really infuriating as I attempt to send Roact objects through RemoteEvents to update it on the server.

**Comment by LPGhatguy** [comment]
We don't generally support sending these objects through `RemoteEvent` or `RemoteFunction` objects because they have unique symbols and are tied to one instance of Roact at a time.

We need many of these tables to be cyclic to support tree traversals in both directions!

**Comment by Jaguar-515** [comment]
Ah well. Thanks for the clarification.
