### ISSUE TITLE
RFC: Achieving React test suite parity under Lua 5.1?

### ISSUE THREAD

**Issue by matthargett** [Roblox/roact#271]
To start exploring the code base, I decided to look at unit tests in React and try to bring more of the same coverage into Roact. I started with this test in React:
https://github.com/facebook/react/blob/da834083cccb6ef942f701c6b6cecc78213196a8/packages/react/src/__tests__/ReactCreateRef-test.js#L23
```js
  it('should warn in dev if an invalid ref object is provided', () => {
```

My code looks like this:
```lua
	local Component = require(script.Parent.Component)
	local createElement = require(script.Parent.createElement)
	local createReconciler = require(script.Parent.createReconciler)
	local createRef = require(script.Parent.createRef)
	local Logging = require(script.Parent.Logging)
	local NoopRenderer = require(script.Parent.NoopRenderer)
	local Ref = require(script.Parent.PropMarkers.Ref)
	local Type = require(script.Parent.Type)

	local noopReconciler = createReconciler(NoopRenderer)

	it("should throw if invalid ref object provided", function()
		function Wrapper(children)
			return children;
		end

		local ExampleComponent = Component:extend("ExampleComponent")

		local tree = createElement(Wrapper, {
			Value = createElement(ExampleComponent, {
				Value = "Foo",
				[Ref] = {}
			}),
		})

		local logInfo = Logging.capture(function()
			NoopRenderer.mountHostNode(noopReconciler, tree)
		end)

		expect(#logInfo.errors).to.equal(1)
	end)
```

Good news: The test does run! Bad news: The NoopRenderer doesn't emit the warnings like React's TestRenderer does. Roact *does* have this warning, but it's only in the RobloxRenderer. When I use the RobloxRenderer instead of the NoopRenderer, it gives an error that implies that the particular module cannot really run in POL (Plain Old Lua).

It looks like React has extracted some of this logic out into common files that are shared between renderers, hence it can unit test this specific behavior in the TestRenderer. 

My question, hence the RFC: should I refactor this code to better match the current structure of the React codebase so that:
1. I can better align the tests, and run them in base Lua 5.1 for easier public CI/CD
2. It becomes easier to port relevant bug fixes and optimizations from React into Roact
3. It further lowers the barrier to entry for folks coming from a React background
4. React and Roact documentation and community support forums (StackOverflow) can have more overlap

I swear I was trying a simple starter task, and stumbled backward into this. I'm very open to alternate suggestions, including skipping this test and trying for a simpler one! :D

Thanks in advance for any guidance!

**Comment by jhampton** [comment]
For hygiene, I'm bumping this RFC.  I believe this will be moot, but should this particular RFC be closed at this time @matthargett ?

**Comment by matthargett** [comment]
Yes, it should be closed. Good news is on the way on this front!
