### ISSUE TITLE
How to comunicate with sibling component ?

### ISSUE THREAD

**Issue by dolfijn3000** [Roblox/roact#286]
Hello everyone.

I'm new to roact and I'm experimenting with it. I have a frame with a button in. it this frame is called frame1. I also have a second frame, frame2. each frame is a component in a module script. I then have the main component that has a screen GUI and loads the two frame components. frame wan is standard visible, frame2 is standard invisible. What I want to achieve is when the button in frame 1 is pressed, frame1 disappears and frame2 appears. How can I achieve this ? how do I communicate between sibling components ?

**Comment by ZoteTheMighty** [comment]
Hi! In situations where sibling components need a shared awareness of some state, you may want to lift state up to a parent component, which owns the state and forwards it to its children via props.

Check out [this article from React's docs](https://reactjs.org/docs/lifting-state-up.html) that describes this concept in more detail.
