### ISSUE TITLE
A way to use Roact with Roblox-TS(Typescript)

### ISSUE THREAD

**Issue by CertifiedRice** [Roblox/roact#299]
Some people(including me) like to use TypeScript to make Roblox games. I think it would be a good idea to add TypeScript support to Roact.

**Comment by daimond113** [comment]
I think it exists already, https://github.com/roblox-ts/rbx-roact

**Comment by CertifiedRice** [comment]
:P ty

**Comment by tacheometry** [comment]
@CertifiedRice please look at https://roblox-ts.com/docs/guides/roact-jsx. There's built in support.
