### ISSUE TITLE
setState can't remove values from state

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#30]
React is a JavaScript library, which means that it was designed around the existence of both `null` and `undefined`.

In React, if you want to remove a value from your state, you can use:
```js
this.setState({
    foo: null
})
```

In Lua with Roact, if you try the same thing, you'll realize it doesn't do anything:
```lua
self:setState({
    foo = nil
})
```

Lua doesn't have a way to differentiate between "nothing" and "absent" in tables! This is an API hole in Roact!

We need some way to remove a value from the state!

Two potential solutions:

* Introduce `self:removeFromState(key)`
    * This means that operations that do both a `setState` and a `removeFromState` will trigger two re-renders right now D:
* Add `Symbol` value that represents `nil`
    * There's no case where this value would end up in your state accidentally, but what would we call this symbol? `Roact.None`?

**Comment by LPGhatguy** [comment]
After talking with people and sleeping on it, I think introducing `Roact.None` for cases like this would be beneficial.

**Comment by Biack1st** [comment]
any update?

**Comment by abagh0703** [comment]
@Biack1st you can use `Roact.None` https://roblox.github.io/roact/api-reference/#roactnone
