### ISSUE TITLE
New Context API

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#4]
Right now, adding a value to Roact's context API looks like this:

```lua
function MyComponent:init()
	self._context.blah = "foo"
end
```

Since we originally built Roact, the React team designed and implemented an [entirely new context API](https://reactjs.org/docs/context.html) that's a lot nicer. I think we should steal it wholesale, since it's exactly what we recommend people build on top of `_context` anyways:

```lua
local ThemeContext = Roact.createContext("default value")

local function UsingValue()
	return Roact.createElement(ThemeContext.Consumer, {
		render = function(theme)
			return Roact.createElement("TextLabel", {
				Text = theme,
			})
		end,
	})

	-- We could also introduce a helper live we've done for other context-using
	-- libraries in the past:

	return ThemeContext.with(function(theme)
		return Roact.createElement("TextLabel", {
			Text = theme,
		})
	end)
end

local function Root()
	return Roact.createElement(ThemeContext.Provider, {
		value = "overridden value",
	}, {
		Inner = Roact.createElement(UsingValue),
	})
end
```

Some notable changes from the old context API:
* No ability to explicitly access the internal context table, only the keys you've created
* Context values will update when the provider is updated (!!)
* Not possible to pull context values without also subscribing to their updates

I'm on the fence a bit about the `contextType` API that React has, but it would be useful for components that need to use context values outside of `render`.

**Comment by LPGhatguy** [comment]
https://github.com/acdlite/rfcs/blob/new-version-of-context/text/0000-new-version-of-context.md

**Comment by LPGhatguy** [comment]
I've stalled out on this.

Because of versioning confusion, I'm going to cut this from the 1.0 milestone and introduce it at a later date. It's just too important to start incrementing real version numbers for documentation purposes.

**Comment by psewell** [comment]
This is a proposal based on [this "Context 2" proposal](https://trello.com/c/YnJoIeop) from the Studio DeveloperFramework work in progress, based on how it would look if it was implemented directly into Roact.

The Context 2 proposal was designed with scalability in mind, in particular to fix forcing the consumer to define a component that manually stacks providers, and having to stack `with` functions when using multiple items from context. The former is a minor annoyance and has produced multiple competing standards on how these files should be formatted. The latter issue produces rightward drift in functions and results in changelists of large amounts of whitespace.

**Example Usage:**
```lua
-- Theme file
local Theme = Roact.ContextItem:extend("Theme")

-- ContextItem requires us to define a 'createProvider' function
function Theme:createProvider(root)
	return Roact.createElement(Roact.Provider, {
		ContextItem = self,
		-- Optionally, we can provide an UpdateSignal signal as a prop, to
		-- have this ContextItem re-render listeners when it updates.
		-- UpdateSignal = Signal.new(),
	}, {root})
end

-- Outside of createProvider, the ContextItem is free to
-- define its own implementation and API. The Theme instance
-- is what will ultimately get passed into and read from context.
function Theme.new(item)
	self = {
		item = item,
	}

	setmetatable(self, Theme)
	return self
end

function Theme:get()
	return self.item
end

-- UsingValue file
local Theme = require(Theme)
local UsingValue = Roact.PureComponent:extend("UsingValue")

function UsingValue:render()
	local theme = self.props.Theme
	return Roact.createElement("TextLabel", {
		Text = theme:get(),
	})
end

-- We use mapContextToProps, which can accept any number of
-- ContextItems in its input mapping. This prevents rightward
-- drift that occurs if we use 'with' functions. We can also use this
-- mapping to handle any naming collisions, if they were to occur.
Roact.mapContextToProps(UsingValue, {
	Theme = Theme,
}

return UsingValue

-- Root file
local Theme = require(Theme)
local theme = Theme.new("Hello World")

local function Root()
	-- Thanks to ContextItems defining their own createProvider method,
	-- we can have a static method that accepts any number of
	-- ContextItem instances and creates a provider for each, thus preventing
	-- the user from having to write their own stack of Providers.
	return Roact.provideContext({theme}, {
		Inner = Roact.createElement(UsingValue),
	})
end
```
