### ISSUE TITLE
Get rid of Core, refactor into several files

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#47]
I don't think there's any reason to have a giant file called `Core`.

Instead, I'd like to break pretty much everything in that file into its own file and be more selective about what's exported in the public API, which would probably include explicitly laying out each export and getting rid of the giant `apply` function.

**Comment by LPGhatguy** [comment]
1.0 can move on without this, but this is still a good idea.

**Comment by AmaranthineCodices** [comment]
Do you still want to do this, or can I write a PR for it?

**Comment by LPGhatguy** [comment]
I think I'd like to do it. It's not really that interesting of a problem.

**Comment by AmaranthineCodices** [comment]
Okay!
