### ISSUE TITLE
New reconciler

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#48]
The reconciler is starting to get pretty darn big, complicated, and a bit convoluted.

I'd like to take another stab at rewriting it from the ground up with better-defined types, and to be a little bit more robust.

My wishlist for the new reconciler:
* [Asynchronous Rendering](https://github.com/Roblox/roact/issues/18)
* [Fragments](https://github.com/Roblox/roact/issues/7)
* Better error handling, resolving #55 and #84
* New 'tree root' object, resolving #89 and #90
* Foundation for new context API, from #4
* [Refactored portals](https://github.com/Roblox/roact/issues/8)
* Better `setState` behavior, resolving #56 and #71
* Support for multiple/alternative reconcilers, for out-of-Roblox use and unit testing
* Complete test coverage!

**Comment by AmaranthineCodices** [comment]
One idea I keep coming back to related to this: *what if we had multiple reconcilers?* - or at least the capability to support multiple reconcilers?

It'd be really cool to have:

* `ShallowReconciler`, like React's [ShallowRenderer](https://reactjs.org/docs/shallow-renderer.html) - this is used for unit testing. It renders only a component's root return value and its immediate children, and no further.
* `TestReconciler`, like React's [TestRenderer](https://reactjs.org/docs/test-renderer.html) - this is also used for unit testing. It completely renders a component tree to a series of objects.

**Comment by LPGhatguy** [comment]
I updated the issue with a complete wishlist of the things I'm looking for in the new reconciler.
