### ISSUE TITLE
Add getDerivedStateFromProps

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#53]
React provides a lifecycle hook named [componentWillReceiveProps](https://reactjs.org/docs/react-component.html#componentwillreceiveprops). It is invoked with the next property table, which may or may not be equal to the current one. Crucially, it *allows `setState` to be called* within it, allowing components to respond to props with a change in state.

This would be very beneficial to have in Roact. Potential use-cases include:

* Changing a button's `hover` state if its position changes
* Resizing a component (implementing your own `SizeFromContents`, for example) in response to property changes
* Fixing https://github.com/Roblox/roact-rodux/issues/2

**Comment by LPGhatguy** [comment]
I don't think I ever used this in React, so I'm not sure about its exact behavior.

Does calling `setState` inside `willReceiveProps` just change the state without triggering a re-render? Where does this happen in relation to `shouldUpdate`?

Should we wait for the new reconciler that I'll build someday™?

**Comment by AmaranthineCodices** [comment]
I'm not entirely sure how it behaves in React either.

I think calling `setState` here should *not* trigger a re-render just because of the setState call. The component will still probably be re-rendered because of the properties change. The update flow would be something like:

```
willReceiveProps -> shouldUpdate -> willUpdate -> render -> didUpdate
```

I'm not sure how it would interact with asynchronous rendering; it's kind of tricky to contemplate. As for waiting on the new reconciler, I'm not sure - it should be fairly easy to apply this to the current reconciler, but I've not had a look at it yet.

**Comment by LPGhatguy** [comment]
There's a new blog post today from the React team that mentions `componentWillReceiveProps` and specifically that it's not a good idea, heh.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

It introduces a `getDerivedStateFromProps` method that I _really_ like the idea of. I wonder if that's enough to implement what we're looking for?

**Comment by AmaranthineCodices** [comment]
It'd require some changes to Roact-Rodux, but `getDerivedStateFromProps` should work for what we want it to do. The major change that has to be made to Roact-Rodux is where we store the state. Currently we get it from context in the constructor:

```lua
local store = self._context[storeKey]
```

And store it as a member of the component, *not* in state:

```lua
self.store = store
```

This can be fixed by storing the store in the wrapper component's state or by giving `getDerivedStateFromProps` access to context. The latter might constraint asynchronous rendering and context changes, but I'm not sure.
