### ISSUE TITLE
Include LICENSE file in rbxmx distribution?

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#54]
With `rbxpacker`, the distribution system let us include `LICENSE` as a `StringValue` object contained within the library. The manual model builds I've  pushed up for 1.0.0-pre2 don't have a license included in their XML.

I'm not sure how useful it would be to include that license moving forward because the text of the Apache 2.0 license is kind of large. You really don't want to send 3-4 copies of it to your clients when creating a game using Roact, Rodux, and Roact-Rodux.

**Comment by AmaranthineCodices** [comment]
I don't think it's worth building the license in at this stage, since anyone downloading it will probably get it from this repository, where the license can be easily accessed.
