### ISSUE TITLE
createElement should warn if Name or Parent are specified

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#58]
`createElement` should give a warning that the `Name` will be unused if specified in properties - it'll always be overwritten with the key in the children table.

The same should be true for Parent; Roact just overwrites the parent during reification, so setting the Parent property in the element props is a performance hit for no gain.

**Comment by LPGhatguy** [comment]
I'm a little bit apprehensive about tying anything except the reconciler to Roblox's semantics.

I think that the reify/reconcile stages, maybe specifically `_setRbxProp` should warn about this instead of `createElement`.
