### ISSUE TITLE
Rendering instances that cannot be created from scratch

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#61]
A thought I had: right now, Roact doesn't let you declaratively render instances that cannot be created solely by setting Lua properties. The main example of this in Roblox is UnionOperations! You can't create these from scratch; they have some hidden attributes to them that you can only replicate by calling `Clone` on the source UnionOperation. It'd be really cool if Roact could allow you to specify a "source" to use when creating a primitive instance - maybe we can allow instances in `createElement`?

```lua
local element = Roact.createElement(referenceToUnionOperation, {
    Position = Vector3.new(1, 2, 3),
    -- ...
})
```

When a primitive instance with a component of type instance, instead of doing `rbx = Instance.new(component)` when reifying it, we could do `rbx = component:Clone()` instead.

**Comment by LPGhatguy** [comment]
That's a really interesting problem!

I don't know if we want to introduce another way to use `createElement`, because if those objects ever do get mutated by the engine or some other code, the resulting behavior could be really confusing.

Could this feature live entirely in a 'user-land' library?

**Comment by AmaranthineCodices** [comment]
Possibly - let me do some tinkering and see if I can come up with something!

**Comment by LPGhatguy** [comment]
I think a better solution to this problem is creating a component that pulls the un-creatable thing from elsewhere and manages reconciling it.
