### ISSUE TITLE
createRef API like React 16.3

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#70]
React 16.3+ exposes a [new ref API](https://reactjs.org/docs/refs-and-the-dom.html) that's intended to be the default instead of the callback refs that both React and Roact have.

I've found that a lot of users new to the React model try to do things like call `setState` inside refs, or do all sorts of trickery inside of them, when they really should be doing those things in `didMount` instead.

Switching the recommended API to a `createRef`-like API would prevent these issues in the future.

**Comment by AmaranthineCodices** [comment]
This would work way better than function-based refs. I am *skeptical* about one of the details of this:

>When the `ref` attribute is used on a custom class component, the `ref` object receives the mounted instance of the component as its `current`.

This doesn't feel right. It's nice to completely encapsulate component behavior, and this breaks the encapsulation. With this functionality, I can write code that only works when a component is stateful, and mess with its internals arbitrarily. This is not ideal - it feels really imperative, as opposed to the general declarative nature of Roact and React.

**Comment by LPGhatguy** [comment]
I didn't even notice that, that's pretty sketchy.

We can ignore that feature for now, and if we end up really (_really really_) wanting that, we can add it later.

**Comment by AmaranthineCodices** [comment]
I'm working on this locally; should have something in a few days.
