### ISSUE TITLE
Suspend event listeners during reconciliation?

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#71]
A common source of bugs in Roact code that I've seen involves hooking into `Changed` or using `GetPropertyChangedSignal`, and calling `setState` in response.

This pattern is perfectly fine as long as the reconciler doesn't affect the properties you're listening to synchronously. I use this technique in [my Roact Windowing example](https://github.com/LPGhatguy/roact-windowing/blob/b188b803bbb5ce81bb73b4b88dabdce6f1c405dc/src/WindowedScrollingFrame.lua#L74-L75) to make the windowing responsive to your current scroll position.

One idea that @AmaranthineCodices had would be to suspend those events while the reconciler is running, eliminating that entire class of bugs.

Are there any cases where you'd *want* these events? It's only problematic when you end up calling `setState` directly or indirectly.

**Comment by LPGhatguy** [comment]
There is a bit of precedence for this in certain contexts -- React defers re-rendering when `setState` is called inside one of the brower's (synchronous) event handlers.

It's possible that we should do the same thing for events! I imagine this would prevent a lot of bugs, too!

**Comment by ZoteTheMighty** [comment]
This was implemented in #48!!
