### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#80]
Keeping track of APIs that change and keeping everyone up to date is really hard when there aren't version numbers.

I'd like to start tagging APIs in the docs with little numbers like (`1.1+`) so that people can start knowing what will and won't work.

**Comment by LPGhatguy** [comment]
I keep tacking more small things onto the 1.0 milestone, but as it turns out, there's a lot of stuff you have to do before calling a project stable!

**Comment by AmaranthineCodices** [comment]
We did it! :tada:
