### ISSUE TITLE
Rename 'Roact.teardown' to 'Roact.unmount'

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#82]
Having two terms for this in the documentation is kind of confusing.

We can introduce a warning for the `teardown` alias but keep it through 1.0.

**Comment by AmaranthineCodices** [comment]
I think renaming these methods (with warnings for the old names) is a good idea - it makes it a little easier to explain and reason about what's going on. The way I think of it:

* Roact itself reifies / reconciles / tears down components.
* Roact users cause Roact to do these things by mounting / updating / unmounting components.

IMO, reification/reconciliation are internal terms that Roact users shouldn't need to worry about unless they're going to dig into internals!

**Comment by LPGhatguy** [comment]
After a little talk internally, I'm hesitant to change `reconcile` to `update` but I'm still comfortable with the other two changes.

The reason here is that update is sort of a vague term, and talking about reconciliation is a healthy part of learning what Roact is and how you should work with it. It also means our diagnostics can stay very precise about what phase they're referring to ("update phase" is super vague).
