### ISSUE TITLE
Errors put Roact in a bad state

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#84]
The `setState` blocking code can get itself into a bad state if an (unrelated) component causes a bug. This can break everything using Roact if just one failure happens 😱 

There are a couple possible fixes here:
* Introduce an heuristic to let Roact do failure recovery and reset its state
* `pcall` all user methods (this could get expensive 😢)
* Sandbox state like this into a section per disjoint tree
    * This probably isn't a complete solution, but fixes the problem of unrelated code breaking eachother.

**Comment by AmaranthineCodices** [comment]
React has a similar problem that they solve with [error boundaries](https://reactjs.org/docs/error-boundaries.html). I'm not terribly fond of this approach (particularly the whole "define this method for magic behavior" style of creating an error boundary), but it's better than absolutely nothing.

I'm not entirely sure how to do a heuristic for this that catches *every* possible borked state x.x

**Comment by LPGhatguy** [comment]
The cases where Roact mutates an virtual DOM instance and puts it in a bad state are a lot better at least, since they only cause breakage locally!

The `setState` guards are the only thing that I'm suuper worried about with regards to state getting broken in Roact!

**Comment by LPGhatguy** [comment]
I'm bumping this from 1.0.

I think the goal should _not_ be to try to fix up the synchronization error variables, but to instead remove them. We should only introduce errors like this intentionally when absolutely fatal.
