### ISSUE TITLE
Ability to mark a table as a functional component

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/roact#9]
I'm trying to make a functional component. This functional component has some options associated with it. Since ModuleScripts can only return one value, I decided to make the element a table and set its `__call` metamethod to the actual functional component. Roact explodes when you try to reify the component, however, because the type check in `Core.isFunctionalElement` returns `false` for tables (as expected). I don't really want to create a stateful component - there's no need to track state, and adding that for the sole purpose of storing options with the component seems somewhat wasteful.

Simple example:

```lua
local SomeComponent = {}
SomeComponent.Option = {
    A = 1,
    B = 2,
    C = 3,
}

function SomeComponent.Render(props)
    return Roact.createElement("Frame", {
        BackgroundColor3 = Color3.new(props.Option / 3, 0, 0),
    }
end

setmetatable(SomeComponent, { __call = function(_, ...) return SomeComponent.Render(...) end; })
```

Trying to reify `SomeComponent` will produce the following error:
```
ReplicatedStorage.Roact.Reconciler:191: attempt to call field '_new' (a nil value)
Stack Begin
Script 'ReplicatedStorage.Roact.Reconciler', Line 191 - field _reifyInternal
Script 'ReplicatedStorage.Roact.Reconciler', Line 135 - field _reifyInternal (x2)
Script 'ReplicatedStorage.Roact.Reconciler', Line 90 - field reify
-- stack end omitted; leads into user code
```

It'd be nice to be able to indicate to Roact that `SomeComponent` is a functional component, even though it's a table - something like defining a special key (`[Roact.FunctionalTable]` maybe?) in the table. This would let me keep all the enums and such associated with a component with the component itself.

**Comment by LPGhatguy** [comment]
The real solution for this check would be to make `isFunctionalComponent` check for the `_call` metamethod if the argument isn't a function.

I decided against that initially for simplicity.

Is there a reason why you can't just return `SomeComponent.Render` from your ModuleScript or pass `SomeComponent.Render` as your argument to `Roact.createElement`? Doing that would make the separation between "stuff intended for Roact" vs "stuff intended for not-Roact" a little bit cleaner.

**Comment by AmaranthineCodices** [comment]
I can't return `SomeComponent.Render` from the module because I want to be able to refer to the options from the component consumer by name, i.e.

```lua
-- From outside the module
Roact.createElement(SomeComponent, {
    Option = SomeComponent.Option.A
})
```

Using `SomeComponent.Render` as the argument for `Roact.createElement` works; it's just different from most other components, and that has to be communicated in the documentation. This is largely a syntax thing - I'd like for the user of `SomeComponent` to not have to be aware that it needs special handling. Still, it's a minor thing at worst.
